services:
  web:
    image: nginx:latest
    container_name: chat_nginx
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php

  php:
    image: php:8.3.4-fpm
    container_name: chat_php
    volumes:
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
